.github/workflows/linting.yml
=> Run linting automatically on Pull requests and pushed commits

.github/workflows/build.yml, .lintignore, packages/website/package.json
Also added a build command and a file to lintignore
=> Added build pipeline to ensure that the build isn't broken

packages/website/gatsby-config.js, packages/website/package.json, packages/website/postcss.config.js, packages/website/src/components/layout/Layout.js, packages/website/src/layout.css, packages/website/src/pages/index.js, packages/website/tailwind.config.js, yarn.lock
Hei, tenkte det var lettere å gjøre det på denne måten i stedet.
=> tailwind config updated with color profiles (issue)

.github/workflows/deploy-storybook.yml, .github/workflows/linting.yml, packages/website/package.json
Tested it on it's own branch first and that worked
=> Workflow for publishing Storybook to Github Pages

.gitignore, packages/website/gatsby-config.js, packages/website/package.json, packages/website/tailwind.config.js, yarn.lock
Font prefetching og sanity config i gatsby. Det er nå mulig å query data fra sanity-prosjektet (localhost:8000/__graphql)
=> gatsby/sanity connection and font prefetch feature/#23

.dockerignore, Readme.md, cms.Dockerfile, docker-compose.yml, packages/cms/package.json, packages/website/package.json, website.Dockerfile, yarn.lock
Would love your feedback here @Trulsaa since you have worked a bit with Docker.
=> Docker setup

packages/website/src/components/description/index.stories.js, packages/website/src/components/footer/index.js, packages/website/src/components/footer/index.jsx, packages/website/src/components/footer/index.stories.js, packages/website/src/components/footer/index.stories.jsx, packages/website/src/components/layout/index.js, packages/website/src/components/title/index.js, packages/website/src/components/title/index.stories.js, packages/website/tailwind.config.js
=> adding footer component

packages/website/.storybook/main.js, packages/website/.storybook/preview.js, packages/website/package.json, packages/website/postcss.config.js, packages/website/src/components/description/index.stories.js, packages/website/src/components/title/index.stories.js, yarn.lock
Components in Storybook didn't seem correct for me, so I tried changing the tailwind setup a bit so that Storybook would pick it up correctly.
=> Fix tailwind setup for Storybook, as well as Storybook addon controls

.github/workflows/linting-and-test.yml, package.json, packages/website/.babelrc, packages/website/package.json, packages/website/src/components/calltoaction/calltoaction.spec.js, packages/website/src/components/calltoaction/index.jsx, packages/website/src/components/calltoaction/index.stories.jsx, packages/website/src/components/checkbox/checkbox.spec.js, packages/website/src/components/checkbox/index.jsx, packages/website/src/components/checkbox/index.stories.jsx, yarn.lock
Fixes #25
Fixes #53
TODO: style CallToAction component
=> Creating a CallToAction and Checkbox component with tests

Readme.md, packages/infrastructure/Readme.md
Just the folder where I will later push infrastructure code
=> Setup package for infrastructure

.lintignore, Makefile, docker-compose-prod.yml, packages/infrastructure/.gitignore, packages/infrastructure/Readme.md, packages/infrastructure/infrastructure.tf
Prodsetting:
1. Ensure that terraform is up to date:
```
cd packages/infrastructure
terraform plan
```
2. Login to azure (needs `az`-, `jq`- and `docker`-command installed):
```
make az-docker-login
```
3. Build and deploy docker containers:
```
make build-website build-cms
```
4. Run docker compose up:
```
make docker-compose-up
```
You may need to create the docker context `myacicontext`, forgot what command I ran to do that. I think maybe it was created when I first tried to login?
=> First version of prod

packages/cms/schemas/categoryPage.js, packages/cms/schemas/schema.js, packages/cms/schemas/servicePage.js, packages/website/gatsby-node.js, packages/website/src/components/header/index.js, packages/website/src/components/navigation/index.js, packages/website/src/hooks/useLayoutQuery.js, packages/website/src/layout/index.js
While the intended functionality is in place, finishing touches to revert back to original menu layout remains (currently at 80%, will update with an --amend soon).
=> update/create backend schemas and update frontend for dynamic nav func.

.AzureDevOps/pipelines/azure-pipelines.yml, packages/infrastructure/build-steps.yaml, packages/infrastructure/deploy-steps.yaml
Moving the git hash into each of the pipelines so that its not empty on deploy.
=> Fixing deploy pipeline

packages/website/src/components/hero/index.js, packages/website/src/components/icon/index.js
=> fix scroll-to-continue position

packages/website/src/components/blogFilter/BlogFilter.module.css, packages/website/src/components/blogFilter/index.js, packages/website/src/components/blogSection/index.js
=> update filtering behaviour

packages/website/src/components/seo/index.js, packages/website/src/templates/article.js
=> update social share

packages/cms/schemas/categoryPage.js, packages/website/src/templates/category.js
=> default dynamic rendering and sorting of employee cards

packages/cms/schemas/article.js, packages/cms/schemas/externalProfiles.js, packages/cms/schemas/guestAuthor.js, packages/cms/schemas/schema.js, packages/website/src/components/sidebar/index.js, packages/website/src/hooks/useBlogQuery.js, packages/website/src/templates/article.js
=> issue #325

packages/cms/schemas/categoryPage.js, packages/website/src/components/overview/index.js, packages/website/src/templates/category.js
=> flexible overview title #310

.AzureDevOps/pipelines/azure-pipelines-dev.yml, .AzureDevOps/pipelines/azure-pipelines.yml
This Pr merges the new build pipeline scripts into the prod branch.
=> Splitting deployment pipelines, adding scheduled deployment. Fixes #366

.gitignore, packages/cms/scripts/backup.sh, packages/scripts/backup.sh
Should be further developede to add the backup to some storage
=> Add script files that downloads a backup of the sanity production data

packages/website/src/pages/kontakt-oss.js
=> Replace hardcoded phone and email with data from cms

.AzureDevOps/pipelines/azure-pipelines-dev.yml, .AzureDevOps/pipelines/installDependencies.yaml, run
=> Rewrite dev pipeline to use the new run script to deploy website

packages/website-alvb/gatsby-config.js, packages/website-alvb/package.json, yarn.lock
Co-authored-by: Martin Klingenberg <martin.klingenberg@alv.no>
=> Added google-tag-manager to ALV-B (#626)

packages/website-alvb/src/components/videoIntro/index.js, packages/website-alvb/src/pages/index.js
Alters text/video component: display content side-by-side
=> customise video component for alv-b

packages/website/src/pages/blogg.js
Formatted the publishedAt-value to be a properly formatted date. Since most of the readers of our articles are Norwegian I chose to make the locale `no-NB`. The reason being that since this is server-side rendered I would be the server location deciding the language and not the client.
=> Fixed the date-formatting. Using locale-time now

packages/website/src/hookspages/useAboutUsQuery.js, packages/website/src/pages/om-oss.js, packages/website/src/templates/company.js
This PR covers all pages under `/om-oss` right now this is *PERSONALVHÅNDBOKA* and *LIVET  I ALV* from the menu
=> closes #642 Gjorde om company-pages (livet i alv) om til SSR

packages/website/src/templates/company.js
PageTitle data now comes from the serverData object as opposed to the data object 👍
=> fix pageTitle issue

packages/website/gatsby-config.js, packages/website/package.json, yarn.lock
Uses a plugin to generate a robots.txt that points to a sitemap
closes #656
=> Generate robots.txt file for website

packages/website/gatsby-config.js, packages/website/package.json, yarn.lock
closes #672
Should give Jakob superpowers somehow
=> Added linkedin tag to website

packages/website/src/hookspages/useEmployeeQuery.js, packages/website/src/pages/ansatte.js
Closes #643
- Employees with images are loaded using SSR
- Tags for filtering are also loaded through SSR
=> SSR on employee-page 🎇

packages/website/gatsby-config.js
=> New pixel ID for facebook

packages/website/gatsby-config.js, packages/website/package.json, packages/website/src/components/cookieNotice/cookie.module.css, packages/website/src/components/cookieNotice/index.js, packages/website/src/components/layout/index.js, yarn.lock
Added a consent-form to let users allow cookies
- Replaced various plugins for analytics into a single GDPR-friendly
framework
- Tested to see that no tracking is done until the user consents
- Implemented styling using tailwind-css
=> ALV #726 GDPR cookie consent

.AzureDevOps/pipelines/azure-pipelines-mail-api.yml, .AzureDevOps/pipelines/azure-pipelines-website-alvb.yml, .AzureDevOps/pipelines/azure-pipelines-website.yml
One big is not clever. Three small is better
It takes to long to build all the services
Much smarter to divide the big pipeline into three
one for mail, one for website and one for website-alvb
=> Refactored pipelines

packages/shared-components/src/components/productCta/index.js
Loading spinner was spinning for too long. Way too many spins. Reducing spinning time by 400ms worth of spins
=> reduce loading spinner timeout

packages/shared-components/src/components/postCard/index.js, packages/website/src/components/postCard/index.js, packages/website/src/pages/blogg/[slug].js
Dates and duplicate posts are fixed
closes #778
=> Blogg bug-fixes

.github/workflows/pr.yml, packages/cms/schemas/companyPage.js, packages/website/src/hooks/useLayoutQuery.js
We conquer the world through landing-pages
- Added field to schematic
- Filtering the navigation-items through graphql
- In sanity development-tag there is christamas branded data
Check out this route /om-oss/sjult-company-page
closes #664
=> Landing pages that are not in the navigation

packages/website-alvb/src/components/hero/index.js, packages/website-alvb/src/components/localeButtons/index.js, packages/website-alvb/src/components/navigation/index.js, packages/website-alvb/src/components/richTextTypes/index.js, packages/website-alvb/src/components/socialLinks/index.js, packages/website-alvb/src/pages/kontakt-oss.js, website-alvb.nginx.conf
Updated some imports and improved nginx-config
- More filetypes are compressed using gzip
- Improved icon-imports
- Added a 1 day cache policy to nginx-config
=> Performance improvements

packages/shared-components/src/components/breadcrumb/index.jsx, packages/website-alvb/gatsby-node.js, packages/website-alvb/src/templates/company.js, packages/website-alvb/src/utils/navItems.js
New information: rename "services" to "products"
=> rename services to products

packages/website-alvb/src/pages/kontakt-oss.js
Chris requested I remove contact us title and welcome text from alv-b website.
=> remove contact us title and welcome text

packages/shared-components/src/components/blogSlider/index.js, packages/website-alvb/src/components/blogCarousel/index.js, packages/website-alvb/src/components/sidebar/index.js, packages/website-alvb/src/pages/index.js, packages/website-alvb/src/templates/article.js, packages/website-alvb/src/templates/company.js, packages/website/src/components/blogCarousel/index.js, packages/website/src/pages/index.js
Removes more isEnLocale stuff and fixes a new bug where blog carousel slides won't link to blog pages => needed to pass postPrefix variable to get correct link path
=> removing more isEnLocale and fixes blog carousel links

packages/shared-components/src/components/blogSlider/index.js, packages/shared-components/src/components/featuredTeam/index.js, packages/shared-components/src/components/imageTextCards/index.js, packages/shared-components/src/components/imageTextFull/index.js, packages/shared-components/src/components/linkableContent/index.js, packages/shared-components/src/components/navyIntro/index.js, packages/shared-components/src/components/navyIntroImage/index.js, packages/shared-components/src/components/servicesSection/index.js, packages/shared-components/src/components/sidebar/index.js, packages/shared-components/src/components/title/index.js, packages/website-alvb/src/components/richtextAndImage/index.js, packages/website-alvb/src/components/services/index.js, packages/website-alvb/src/components/sidebar/index.js, packages/website-alvb/src/pages/kontakt-oss.js, packages/website/src/components/imageTextHero/index.js, packages/website/src/components/imageTextOverlap/index.js, packages/website/src/components/serviceNavList/index.js, packages/website/src/components/sidebar/index.js, packages/website/src/components/testimonials/index.js, packages/website/src/pages/kontakt-oss.js, packages/website/src/pages/om-oss.js
Both rounded button bug and title colors were caused by the same type of error: competing classnames were added and overrides happened :(
But it's fixed :)
Also updated some conditional logic to adhere to tailwind docs ✌️
=> fix color rendering bugs

packages/shared-components/src/components/header/index.js
Add proper spacing to blog article page header
=> fix blog spacing bug for alvno

packages/website/src/pages/blogg.js
This reverts commit e37fe1c80847480b6807f4c524f7510cc9658643.
=> Revert "add blog page title"

packages/shared-components/src/components/blogSlider/index.js
Responsive img in mobile blog carousel
=> make mobile img responsive

packages/cms/schemas/aboutPage.js, packages/cms/schemas/article.js, packages/cms/schemas/blogCarousel.js, packages/cms/schemas/blogPage.js, packages/cms/schemas/categoryPage.js, packages/cms/schemas/companyPage.js, packages/cms/schemas/landingPage.js, packages/cms/schemas/schema.js, packages/cms/schemas/servicePage.js, packages/shared-components/src/components/blogFilter/index.js, packages/shared-components/src/components/blogSection/index.js, packages/shared-components/src/components/blogSlider/index.js, packages/shared-components/src/components/navyIntro/index.js, packages/website-alvb/src/components/blogCarousel/index.js, packages/website-alvb/src/hookspages/useBlogQueryRecent.js, packages/website/src/components/blogCarousel/index.js, packages/website/src/hooks/useBlogQueryRecent.js, packages/website/src/hooks/useBlogQueryServerSide.js, packages/website/src/hookspages/useServicesQuery.js, packages/website/src/pages/blogg.js, packages/website/src/pages/index.js, packages/website/src/pages/jobbe-i-alv/[slug].js, packages/website/src/pages/om-oss.js, packages/website/src/pages/om-oss/[slug].js, packages/website/src/templates/category.js, packages/website/src/templates/service.js
Makes it possible to have urls set an initial filter config for blog articles with for example:
- alv.no/blogg/?kategori=someCategoryHere
Also fixed an issue where the article card "Read more" text was overlaying the filter background.
=> add initial blog filter by query param

packages/shared-components/src/components/videoIntro/index.js, packages/website/src/pages/index.js
Move text to the right side of the video
=> reintroduce video component to landing page

packages/cms/schemas/ourServicesPage.js, packages/shared-components/src/components/imageTextFull/index.js, packages/website/src/hookspages/useServicesQuery.js, packages/website/src/pages/vi-tilbyr.js
- Makes it possible to select and decide the order of service page cards that show up on /vi-tilbyr page
- Fixes bug where data&analyse section showed cards from systemutvikling
=> fix data & analyse cards and make cards selectable from sanity

packages/shared-components/src/components/cta/index.js, packages/shared-components/src/components/ctaButton/index.js, packages/shared-components/src/components/hire/index.js, packages/shared-components/src/components/icon/index.js, packages/website-alvb/src/components/hero/index.js, packages/website-alvb/src/pages/vårt-team.js, packages/website/src/components/hero/index.js, packages/website/src/components/landingPageHero/index.js, packages/website/src/pages/ansatte.js, packages/website/src/pages/index.js
Change to a more meaningful color setting prop for CtaButton
=> update color prop on cta button

run
Delete the chart folder if it exists in order for the helm pull command to work when deploying mail-api-alvb directly after deploying mail-api in CI
=> Delete the chart folder if it exists

packages/shared-components/src/components/employeeGroup/index.js, packages/shared-components/src/components/gridContainer/index.js
Employee cards weren't showing on initial page load before interactivity on mobile. Now they do
=> fix employees page mobile bug

packages/cms/schemas/brandPackageButton.js, packages/cms/schemas/schema.js, packages/cms/schemas/siteSettings.js, packages/shared-components/src/components/button/index.js, packages/shared-components/src/components/footer/index.js, packages/website/src/components/layout/index.js, packages/website/src/hooks/useLayoutQuery.js
Adds a "download branding material" button to alvno footer
- Sanity schema updates
- Frontend updates
=> brandpackage to footer

packages/shared-components/src/components/blogSlider/index.js, packages/website-alvb/src/components/blogCarousel/index.js, packages/website-alvb/src/pages/index.js, packages/website-alvb/src/templates/company.js, packages/website/src/components/blogCarousel/index.js, packages/website/src/pages/index.js, packages/website/src/pages/om-oss.js, packages/website/src/pages/om-oss/[slug].js, packages/website/src/templates/category.js
Fix blog header color bug and improve props naming for blog carousel
=> improve prop names and fix blogg title color bug

packages/shared-components/src/components/header/index.js, packages/shared-components/src/components/navyIntro/index.js, packages/shared-components/src/components/navyIntroImage/index.js, packages/website/src/components/ctaSection/index.js, packages/website/src/components/layout/layout.css, packages/website/src/components/rolesList/index.js, packages/website/src/components/serviceNavList/index.js, packages/website/src/templates/service.js
Minor improvements here and there to streamline responsive design things
=> responsive updates to category and service pages

packages/shared-components/src/components/linkableContent/LinkableContent.module.css, packages/shared-components/src/components/linkableContent/index.js, packages/shared-components/src/components/richTextTypes/mediaComponent/MediaComponent.module.css, packages/website/src/hooks/useScrollToHeading.js, packages/website/src/pages/om-oss/[slug].js, packages/website/src/templates/service.js
Update styling to linkable headings and add it to service pages
=> Add linkable headings to service pages

.editorconfig, .eslintrc, .github/workflows/pr.yml, .gitignore, package.json, packages/website-alvb/src/config.js, packages/website/src/config.js, packages/website/src/templates/service.js, yarn.lock
- Upgrade eslint
- Remove the blueberrypie dependency
- Add inn some eslint plugin packages directly
=> Upgrade eslint

packages/website/src/components/imageTextHero/index.js, packages/website/src/components/reasonsSlider/index.js, packages/website/src/components/reasonsSlider/sliderStyles.module.css, packages/website/src/pages/jobbe-i-alv.js
- Responsive updates for both hero and carousel sections
- Changed from arrows to dots for carousel navigation
=> update jobb-i-alv hero and carousel design

packages/shared-components/src/components/blockContent/Blockcontent.module.css, packages/shared-components/src/components/linkableContent/index.js, packages/shared-components/src/components/navyIntroImage/index.js, packages/shared-components/src/components/richTextTypes/cta/formCta/FormCta.module.css, packages/shared-components/src/components/richTextTypes/cta/formCta/index.js, packages/shared-components/src/components/richTextTypes/cta/textCta/index.js, packages/shared-components/src/components/richTextTypes/layout/imageTextFlip/index.js, packages/shared-components/src/components/richTextTypes/layout/linkableHeading/index.js, packages/website/src/pages/om-oss/[slug].js, packages/website/src/templates/service.js
=> various styling updates for a more consistent look

packages/cms/schemas/companyPage.js, packages/shared-components/src/components/seo/index.js, packages/website/src/pages/om-oss.js, packages/website/src/pages/om-oss/[slug].js
- Get hero button data from sanity
- Fix bug where selected blog articles didn't show
=> company page button link

packages/website/src/components/imageTextHero/index.js, packages/website/src/components/multicol/index.js, packages/website/src/components/reasonsSlider/index.js, packages/website/src/components/videoCarousel/index.js, packages/website/src/components/videoList/index.js
- VideoList was crashing the page. Put check to see if we were on an IOS device into a useEffect that only runs once.
- Font-weight tweaks
- Adjusted order of image + icon
=> Career page tweaks

packages/video-party/src/pages/index.jsx, packages/video-party/src/styles/global.css, packages/video-party/src/youtube-api.js
- video-party: now it loads all videos in the playlist instead of the 50 first
- video-party: small css size fix
=> video-party: fix for more than 50 videos

packages/mail-api/src/corrId.js, packages/mail-api/src/correlation.js, packages/mail-api/src/index.js, packages/mail-api/src/logger.js, yarn.lock
=> Some small fixes

nginx/website.nginx.conf
Increases body limit for the Nginx load balancer to allow bigger CV upload
=> 962: increase nginx body size limit

Makefile, packages/shared-components/src/components/navItems/index.js, packages/website/src/components/navigation/index.js, packages/website/src/hooks/useLayoutQuery.js, packages/website/src/pages/blogg.js, packages/website/src/pages/vi-tilbyr.js
Changes to navigation to accomodate new category pages
- Small change to navigation styling to look better on a phone
- Made a temporary hard-coded navigigation for category pages
closes #967
=> Issue 967 🔥

packages/website/src/hooks/useLayoutQuery.js
Link did not work as expected
- Was not able to copy and paste the correct slug. This has been fixed
=> Fix penetration Link 🐛

packages/shared-components/src/components/navyIntroImage/index.js, packages/shared-components/src/components/richTextTypes/layout/imageTextFlip/index.js, packages/website/src/templates/service.js, packages/website/src/utils/textutils.js
Small changes to fonts
- Service page title is smaller and suits smaller devices better
- Hyphens removed from service page liks component
- Image flip has higher font weight
=> Service page touches 📦

packages/website/src/components/rolesList/index.js, packages/website/src/pages/blogg.js
Works better on small devices
- Transitioned to a grid-layout that is a little bit different
- Developed as mobile first
- Less component variations
- Mobile breakpoint is now at 700px (seven)
=> Role list rewrite 🔥

packages/website/src/components/rolesList/index.js, packages/website/src/components/videoFilter/index.js
Years now wrap when
- Added wrapping on smaller devices
- Adjusted opacity on category pages widget
=> Video filter wrapping 🐛

packages/website/gatsby-config.js, packages/website/gatsby-node.js, packages/website/plugins/alv-gdpr-tracking/README.md, packages/website/plugins/alv-gdpr-tracking/gatsby-browser.js, packages/website/plugins/alv-gdpr-tracking/package.json, packages/website/plugins/alv-gdpr-tracking/src/index.js, packages/website/plugins/alv-gdpr-tracking/src/services.js, packages/website/plugins/alv-gdpr-tracking/src/utils.js, packages/website/src/components/cookieBanner/index.js, packages/website/src/components/layout/index.js
Due to there being very few good tracking libraries for gatsby I implemented my own GDPR compliant mechanism to handle loading of trackers.
- Supports linkedIn and google tag manager
- Only loads tracker after a user has done a consent
- Simple and responsive design
closes #975
=> Feature #975 🍪

CODEOWNERS
- Remove Mikkel as he has resigned
- Remove Truls as he is busy with a kid
=> 🔨 Update CODEOWNERS

packages/website-alvb/src/components/layout/index.js, packages/website-alvb/src/hookspages/useNavigationQuery.js
Why is this codebase a hostile environment
- Navigation uses toggle found in sanity
- Added types and removed dead properties
=> Navigation fixes 🐛

packages/shared-components/src/components/linkableContent/index.js
- Added some error handling
- This is a bandaid on a broken foot
=> Removing small bug fix 🐛
